#!/usr/bin/env bash

set -eux

# fzf
curl -fsSL https://raw.githubusercontent.com/junegunn/fzf/master/install | /bin/bash

# ripgrep
yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
yum install ripgrep

# cask
curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
cd ~/.emacs.d && cask install --verbose
